GET https://forex.1forge.com/1.0.3/quotes?pairs=EURUSD,GBPJPY,AUDUSD&api_key=bfBuXo30skEAA0ES4Wz3lNQksUjcTuce

GET https://forex.1forge.com/1.0.3/quota?api_key=bfBuXo30skEAA0ES4Wz3lNQksUjcTuce

GET https://forex.1forge.com/1.0.3/symbols?api_key=bfBuXo30skEAA0ES4Wz3lNQksUjcTuce



google-chrome --remote-debugging-port=9222


POST http://localhost:3000/orderBooks/create HTTP/1.1
content-type: application/json

{ 
   "exchangeName": "bitfinex",
    "pair": "BTC-GDP",
    "bid": 6201.56,
    "ask": 6215.15,
    "time": "1530262758920"
}

Get http://localhost:3000/orderBooks/all

Get http://localhost:3000/sever-tcp/start-server
Get http://localhost:3000/sever-tcp/stop-server

Get https://api.coinmarketcap.com/v2/ticker/2546/

Get http://localhost:3000/sever-tcp/user-balance
